return {
  -- Looks cool but can't get paste to work and emoji's are out of date
  -- {
  --   "xiyaowong/telescope-emoji",
  --   keys = {
  --     { "<leader>se", "<cmd>Telescope emoji<cr>", desc = "Emoji" },
  --   },
  -- },

  --  Looks cool, but there are not enough to justify the extra load time
  -- {
  --   "doctorfree/cheatsheet.nvim",
  --   event = "VeryLazy",
  --   dependencies = {
  --     { "nvim-telescope/telescope.nvim" },
  --     { "nvim-lua/popup.nvim" },
  --     { "nvim-lua/plenary.nvim" },
  --   },
  --   config = function()
  --     local ctactions = require("cheatsheet.telescope.actions")
  --     require("cheatsheet").setup({
  --       bundled_cheetsheets = {
  --         enabled = { "default", "lua", "regex" },
  --         disabled = { "nerd-fonts" },
  --       },
  --       bundled_plugin_cheatsheets = {
  --         enabled = {
  --           "telescope.nvim",
  --           "vim-easy-align",
  --         },
  --         disabled = {
  --           "gitsigns",
  --           "vim-sandwich",
  --           "auto-session",
  --           "goto-preview",
  --           "octo.nvim",
  --         },
  --       },
  --       include_only_installed_plugins = true,
  --       telescope_mappings = {
  --         ["<CR>"] = ctactions.select_or_fill_commandline,
  --         ["<A-CR>"] = ctactions.select_or_execute,
  --         ["<C-Y>"] = ctactions.copy_cheat_value,
  --         ["<C-E>"] = ctactions.edit_user_cheatsheet,
  --       },
  --     })
  --   end,
  -- },
}
