# Homebrew completions
if type brew &>/dev/null; then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi

autoload -Uz compinit
compinit

alias lg='lazygit'
alias vim='nvim'

eval "$(starship init zsh)"
export PATH="$HOME/.local/bin:$PATH"
