# Homebrew completions
if type brew &>/dev/null; then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi

autoload -Uz compinit
compinit

alias lg='lazygit'
alias vim='nvim'
alias ls='eza'
alias ll='eza -lah --git'
alias lt='eza --tree --level=2'
alias la='eza -a'

eval "$(starship init zsh)"
export PATH="$HOME/.local/bin:$PATH"
