#!/usr/bin/bash

# setup direnv in the current directory

if type direnv >/dev/null 2>&1
then
    show_virtual_env() {
        if [[ -n "$VIRTUAL_ENV" && -n "$DIRENV_DIR" ]]; then
            echo "($(basename $VIRTUAL_ENV))"
        fi
    }
    export -f show_virtual_env
    PS1='$(show_virtual_env) '$PS1
    eval "$(direnv hook bash)"
fi
