#!/usr/bin/bash

# setup direnv in the current directory

if type direnv >/dev/null 2>&1
then
    show_virtual_env() {
        if [[ -n "$CONDA_DEFAULT_ENV" ]]; then
            VENV=$CONDA_DEFAULT_ENV
        else
            VENV=$VIRTUAL_ENV
        fi
        if [[ -n "$VENV" && -n "$DIRENV_DIR" ]]; then
            echo "($(basename $VENV)) "
        fi
    }
    export -f show_virtual_env
    PS1='$(show_virtual_env)'$PS1
    eval "$(direnv hook bash)"
fi
