#!/usr/bin/bash

# Setup FZF in your shell

if [[ -r /usr/share/fzf/shell/key-bindings.bash ]]
then
    # CTRL-T: select file
    # CTRL-R: select history
    # ALT-C:  cd to select directory
    . /usr/share/fzf/shell/key-bindings.bash

    export FZF_DEFAULT_OPTS='--height=40% --layout=reverse --border --info=inline'

    # Use fd instead of the default find
    export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude=.git --exclude=node_modules --no-ignore-vcs'
    export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND

    _fzf_compgen_path() {
        fd --hidden --follow --exclude ".git" --exclude "node_modules" . "$1"
    }

    # Use fd to generate the list for directory completion
    _fzf_compgen_dir() {
        fd --type d --hidden --follow --exclude ".git" --exclude "node_modules" . "$1"
    }
fi
