#!/bin/bash

# User specific environment and startup programs

# Redefine pathmunge which gets unset at end of /etc/profile
pathmunge() { #
    # Insert a new element into your path is not already there
    # Stolen from /etc/profile
    #
    # skip non-existent directories
    [[ -d $1 ]] || return
    if ! echo "$PATH" | /bin/grep -E "(^|:)$1($|:)" 1>/dev/null 2>&1; then
        if [ "$2" = "after" ]; then
            PATH=$PATH:$1
        else
            PATH=$1:$PATH
        fi
    fi
}

#> prepend in this order
pathmunge /sbin after
pathmunge /usr/sbin after
pathmunge /usr/local/sbin after
pathmunge "$HOME/.local/bin"
pathmunge "$HOME/bin"

## interactive variables

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'
export RSYNC_RSH=ssh
export LESS="-R"
unset MAILCHECK

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"

# This can help with some clipboard issues
export QT_QPA_PLATFORM=wayland

# I never use these
export XDG_DESKTOP_DIR="$HOME"
export XDG_TEMPLATES_DIR="$HOME"
export XDG_PUBLICSHARE_DIR="$HOME"

if [[ -d "$HOME/.cargo/bin" ]]; then
    pathmunge "$HOME/.cargo/bin"
fi

# Buildkit does not work well in fedora
export DOCKER_BUILDKIT=0
export COMPOSE_BAKE=false

################################################################################

export PATH
unset pathmunge

# Use separate history file for Claude Code sessions
if [[ -n "$CLAUDECODE" ]]; then
    export HISTFILE=~/.claude_history
fi

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi
