#!/usr/bin/bash


if [[ -d /home/kal/.pyenv/ ]];
then
    source '/home/kal/.pyenv/libexec/../completions/pyenv.bash'
    command pyenv rehash 2>/dev/null
    pyenv() {
    local command
    command="${1:-}"
    if [ "$#" -gt 0 ]; then
        shift
    fi

    case "$command" in
    activate|deactivate|rehash|shell)
        eval "$(pyenv "sh-$command" "$@")";;
    *)
        command pyenv "$command" "$@";;
    esac
    }
fi

